[package]
name = "stopwatchd"
version = "0.1.0"
edition = "2021"
authors = ["RenoirTan"]
description = "Stopwatch daemon in the terminal."
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "stopwatchd"
path = "src/lib/mod.rs"
test = true
crate-type = ["lib"]

[[bin]]
name = "swd"
path = "src/bin/swd/mod.rs"

[dependencies]
