[package]
name = "stopwatchd"
version = "0.1.0"
edition = "2021"
authors = ["RenoirTan"]
description = "Stopwatch daemon in the terminal."
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "stopwatchd"
path = "src/lib/mod.rs"
test = true
crate-type = ["lib"]

[[bin]]
name = "swd"
path = "src/bin/swd/mod.rs"

[[bin]]
name = "sw-start"
path = "src/bin/sw-start/mod.rs"

[[bin]]
name = "sw-info"
path = "src/bin/sw-info/mod.rs"

[[bin]]
name = "sw-stop"
path = "src/bin/sw-stop/mod.rs"

[[bin]]
name = "sw-lap"
path = "src/bin/sw-lap/mod.rs"

[dependencies]
ciborium = "0.2.0"
clap = { version = "4.1.4", features = ["derive"] }
futures = "0.3.26"
log = "0.4.17"
serde = { version = "1.0.152", features = ["derive"] }
signal-hook = "0.3.14"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
syslog = "6.0.1"
tokio = { version = "1.25.0", features = ["rt", "macros", "rt-multi-thread", "net", "sync", "io-util"] }
uuid = { version = "1.3.0", features = ["v4", "serde"] }
