[package]
name = "stopwatchd"
version = "0.1.0"
edition = "2021"
authors = ["RenoirTan"]
description = "Stopwatch daemon in the terminal."
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
