#!/bin/bash

set -e

source "$(dirname $0)/_common"

setup_dirvars
print_dirvars

cd_src

echo 'Building stopwatchd... '
cargo build --release --features "${features}"
echo 'OK!'

if is_var "${use_systemd}"; then
    scripts/mk-systemd-service
fi