#!/bin/bash

set -e

source "$(dirname $0)/_common"

setup_dirvars
print_dirvars

cd_src

echo 'Building stopwatchd... '
if [ -z "${features}"]; then
    cargo build --release --features "${features}"
else
    cargo build --release --no-default-features --features "${features}"
fi
echo 'OK!'

if is_var "${use_systemd}"; then
    scripts/mk-systemd-service
fi