#!/bin/bash

source "$(dirname $0)/_common"

_serviceoutpath="stopwatchd.service"

setup_dirvars

cd_src

if [ ! -f "${_servicepath}" ]; then
    echo "${_servicepath} does not exist. It may have been deleted or moved."
    exit 1
fi

install -Dm 644 "${_servicepath}" "${outdir}/${_serviceoutpath}"
sed -i "s|<BINDIR>|${bindir}|" "${outdir}/${_serviceoutpath}"