#!/bin/bash

pkgdir="$(pwd)/pkg"
prefix="/usr"
_reldir="./target/release"
_swdpath="${_reldir}/swd"
_swctlpath="${_reldir}/swctl"
_servicepath="./res/init/systemd/stopwatchd.service"

while getopts "d:" option; do
    case "${option}" in
        d)
            echo "Specified custom packaging directory: ${option}"
            pkgdir="${option}"
            ;;
        p)
            echo "Specified prefix: ${option}"
            prefix="${option}"
            ;;
        ?)
            echo "Usage: $(basename $0) [-d pkgdir]"
            echo ""
            echo "Options:"
            echo " -d pkgdir: Set the directory to package stopwatchd."
            echo "          : '$(pwd)/pkg' by default."
            exit 1
            ;;
    esac
done

cd "$(dirname $0)/.."

if [ ! -d "${_reldir}" ]; then
    echo "${_reldir} not found. Build the package before continuing."
    exit 1
fi

if [ ! -f "${_swctlpath}" ]; then
    echo "swctl not found in ${_reldir}. Recompile and try again."
    exit 1
fi

if [ ! -f "${_swdpath}" ]; then
    echo "swd not found in ${_reldir}. Recompile and try again."
    exit 1
fi


mkdir -p "${pkgdir}"

install -Dm 755 "${_swdpath}" "${pkgdir}/${prefix}/bin/swd"
install -Dm 755 "${_swctlpath}" "${pkgdir}/${prefix}/bin/swctl"

install -Dm 644 "${_servicepath}" "${pkgdir}/${prefix}/lib/systemd/system/stopwatchd.service"
sed -i "s|<PREFIX>|${prefix}|" "${pkgdir}/${prefix}/lib/systemd/system/stopwatchd.service"